using Zeno.Core.Vectors;

namespace Zeno.Core.Matrices;

public class Matrix : IMatrix
{
    private double[,] _elements;

    public Matrix(int rows, int cols)
    {
        if (rows <= 0 || cols <= 0)
            throw new ArgumentException("Rows and Columns must be greater than zero!");

        Rows = rows;
        Cols = cols;

        _elements = new double[rows, cols];
    }

    public Matrix(double[,] elements)
    {
        Rows = elements.GetLength(0);
        Cols = elements.GetLength(1);
        _elements = (double[,])elements.Clone();
    }

    public Matrix(Matrix matrix)
    {
        _elements = (double[,])matrix.Elements.Clone();
    }

    public double this[int row, int col]
    {
        get
        {
            if (row < 0 || row >= Rows || col < 0 || col >= Cols)
                throw new IndexOutOfRangeException("Index is out of range!");

            return _elements[row, col];
        }
        set
        {
            if (row < 0 || row >= Rows || col < 0 || col >= Cols)
                throw new IndexOutOfRangeException("Index is out of range!");

            _elements[row, col] = value;
        }
    }

    public int Rows { get; }
    public int Cols { get; }
    public string Shape
    {
        get => $"{Rows}x{Cols}";
    }
    public double[,] Elements
    {
        get => _elements;
        set => _elements = value ?? throw new ArgumentNullException(nameof(value));
    }

    public Matrix Transpose()
    {
        Matrix matrixT = new(Cols, Rows);

        for (int i = 0; i < Rows; i++)
        for (int j = 0; j < Cols; j++)
            matrixT[j, i] = _elements[i, j];

        return matrixT;
    }

    public double Trace()
    {
        double trace = 0;

        for (int i = 0; i < Rows; i++)
            trace += _elements[i, i];

        return trace;
    }

    public double[] Flatten()
    {
        return _elements.Cast<double>().ToArray();
    }

    public static Matrix Identity(int size)
    {
        Matrix matrix = new(size, size);

        for (int i = 0; i < size; i++)
            matrix[i, i] = 1;

        return matrix;
    }

    public static Matrix KroneckerProduct(Matrix a, Matrix b)
    {
        int newRows = b.Rows * a.Rows;
        int newCols = b.Cols * a.Cols;
        Matrix result = new(newRows, newCols);

        // convert each matrix into an array
        double[] aflat = a.Flatten();
        double[] bflat = b.Flatten();

        // 'SelectMany' projects each element of aflat array into a sequence of results
        // generated by multiplying it with each element of bflat.
        double[] abflat = aflat.SelectMany(x => bflat.Select(y => x * y)).ToArray();

        // for (int m = 0; m < newRows; m++)
        // for (int n = 0; n < newCols; n++)
        // for (int x = 0; x < a.Rows; x++)
        // for (int y = 0; y < a.Cols; y++)
        //     result[m, n] = a[x, y] * b[x, y];

        return result;
    }

    public static Matrix operator +(Matrix a, Matrix b)
    {
        if (!a.Shape.Equals(b.Shape))
            throw new ArgumentException(
                "Matrix addition requires that Matrices must have the same dimensions!"
            );

        Matrix result = new(a.Rows, a.Cols);

        for (int i = 0; i < a.Rows; i++)
        for (int j = 0; j < a.Cols; j++)
            result[i, j] = a[i, j] + b[i, j];

        return result;
    }

    public static Matrix operator -(Matrix a, Matrix b)
    {
        if (!a.Shape.Equals(b.Shape))
            throw new ArgumentException(
                "Matrix subtration requires that Matrices must have the same dimensions!"
            );

        Matrix result = new(a.Rows, a.Cols);

        for (int i = 0; i < a.Rows; i++)
        for (int j = 0; j < a.Cols; j++)
            result[i, j] = a[i, j] - b[i, j];

        return result;
    }

    public static Matrix operator *(Matrix a, double scalar)
    {
        Matrix result = new(a.Rows, a.Cols);

        for (int i = 0; i < a.Rows; i++)
        for (int j = 0; j < a.Cols; j++)
            result[i, j] = scalar * a[i, j];

        return result;
    }

    public static Matrix operator *(Matrix a, Matrix b)
    {
        if (!a.Shape.Equals(b.Shape))
            throw new ArgumentException(
                "Matrix multiplication requires that Matrices must have the same dimensions!"
            );

        Matrix result = new(a.Rows, a.Cols);

        for (int i = 0; i < a.Rows; i++)
        for (int j = 0; j < a.Cols; j++)
        for (int k = 0; k < a.Cols; k++)
            result[i, j] += a[i, k] * b[k, j];

        return result;
    }

    public static Vector operator *(Matrix matrix, Vector vector)
    {
        if (matrix.Cols != vector.Dimensions)
            throw new ArgumentException("Matrix columns must match vector dimenions!");

        double[] result = new double[vector.Dimensions];

        for (int i = 0; i < matrix.Rows; i++)
        for (int j = 0; j < matrix.Cols; j++)
            result[i] += matrix[i, j] * vector[j];

        return new Vector(result);
    }

    public static Vector3 operator *(Matrix matrix, Vector3 vector)
    {
        if (matrix.Cols != vector.Dimensions)
            throw new ArgumentException("Matrix columns must match vector dimenions!");

        double[] result = new double[vector.Dimensions];

        for (int i = 0; i < matrix.Rows; i++)
        for (int j = 0; j < matrix.Cols; j++)
            result[i] += matrix[i, j] * vector[j];

        return new Vector3(result);
    }

    public static Vector2 operator *(Matrix matrix, Vector2 vector)
    {
        if (matrix.Cols != vector.Dimensions)
            throw new ArgumentException("Matrix columns must match vector dimenions!");

        double[] result = new double[vector.Dimensions];

        for (int i = 0; i < matrix.Rows; i++)
        for (int j = 0; j < matrix.Cols; j++)
            result[i] += matrix[i, j] * vector[j];

        return new Vector2(result);
    }
}
